{
 "title": "Protocol circuits",
 "description": "Metrics relating to protocol circuits",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "protocol_circuit",
    "label": "Protocol circuit",
    "query": {
     "query": "label_values(aztec_circuit_protocol_circuit_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Circuit proving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Circuit proving",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aztec_circuit_proving_duration_milliseconds{aztec_circuit_protocol_circuit_name=\"base-parity\"}",
     "legendFormat": "Base parity"
    },
    {
     "expr": "aztec_circuit_proving_duration_milliseconds{aztec_circuit_protocol_circuit_name=\"root-parity\"}",
     "legendFormat": "Root parity"
    },
    {
     "expr": "aztec_circuit_proving_duration_milliseconds{aztec_circuit_protocol_circuit_name=\"base-rollup\"}",
     "legendFormat": "Base rollup"
    },
    {
     "expr": "aztec_circuit_proving_duration_milliseconds{aztec_circuit_protocol_circuit_name=\"merge-rollup\"}",
     "legendFormat": "Merge rollup"
    },
    {
     "expr": "aztec_circuit_proving_duration_milliseconds{aztec_circuit_protocol_circuit_name=\"root-parity\"}",
     "legendFormat": "Root rollup"
    }
   ]
  },
  {
   "title": "Circuit witness generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aztec_circuit_witness_generation_duration_milliseconds{aztec_circuit_protocol_circuit_name=\"base-parity\"}",
     "legendFormat": "Base parity"
    },
    {
     "expr": "aztec_circuit_witness_generation_duration_milliseconds{aztec_circuit_protocol_circuit_name=\"root-parity\"}",
     "legendFormat": "Root parity"
    },
    {
     "expr": "aztec_circuit_witness_generation_duration_milliseconds{aztec_circuit_protocol_circuit_name=\"base-rollup\"}",
     "legendFormat": "Base rollup"
    },
    {
     "expr": "aztec_circuit_witness_generation_duration_milliseconds{aztec_circuit_protocol_circuit_name=\"merge-rollup\"}",
     "legendFormat": "Merge rollup"
    },
    {
     "expr": "aztec_circuit_witness_generation_duration_milliseconds{aztec_circuit_protocol_circuit_name=\"root-parity\"}",
     "legendFormat": "Root rollup"
    }
   ]
  },
  { "title": "Circuit simulation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Circuit simulation (only when faking proofs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(aztec_circuit_simulation_duration_milliseconds_sum{aztec_circuit_protocol_circuit_name=\"base-parity\"}[$__rate_interval]) / rate(aztec_circuit_simulation_duration_milliseconds_count{aztec_circuit_protocol_circuit_name=\"base-parity\"}[$__rate_interval])",
     "legendFormat": "Base paritiy"
    },
    {
     "expr": "rate(aztec_circuit_simulation_duration_milliseconds_sum{aztec_circuit_protocol_circuit_name=\"root-parity\"}[$__rate_interval]) / rate(aztec_circuit_simulation_duration_milliseconds_count{aztec_circuit_protocol_circuit_name=\"root-parity\"}[$__rate_interval])",
     "legendFormat": "Root paritiy"
    },
    {
     "expr": "rate(aztec_circuit_simulation_duration_milliseconds_sum{aztec_circuit_protocol_circuit_name=\"base-rollup\"}[$__rate_interval]) / rate(aztec_circuit_simulation_duration_milliseconds_count{aztec_circuit_protocol_circuit_name=\"base-rollup\"}[$__rate_interval])",
     "legendFormat": "Base rollup"
    },
    {
     "expr": "rate(aztec_circuit_simulation_duration_milliseconds_sum{aztec_circuit_protocol_circuit_name=\"merge-rollup\"}[$__rate_interval]) / rate(aztec_circuit_simulation_duration_milliseconds_count{aztec_circuit_protocol_circuit_name=\"merge-rollup\"}[$__rate_interval])",
     "legendFormat": "Merge rollup"
    },
    {
     "expr": "rate(aztec_circuit_simulation_duration_milliseconds_sum{aztec_circuit_protocol_circuit_name=\"root-rollup\"}[$__rate_interval]) / rate(aztec_circuit_simulation_duration_milliseconds_count{aztec_circuit_protocol_circuit_name=\"root-rollup\"}[$__rate_interval])",
     "legendFormat": "Root rollup"
    }
   ]
  }
 ]
}